# Site settings
title: OSS Development # site title
description: 'Artificial Intelligence trends and concepts made easy.'
permalink : ':title:output_ext'
baseurl : "/"
url : "https://themvm.github.io"
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon=SEO: "/assets/img/branding/MVM-symbol-black.png"
